### ISSUE TITLE
ha log 报错了,应该是天气接口方面的问题

### ISSUE THREAD

**Issue by houoop** [zllikey/AirnutFun#1]
Logger: root
Source: custom_components/airnut/__init__.py:111
Integration: Fun (documentation)
First occurred: 12:24:43 (1 occurrences)
Last logged: 12:24:43

Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/config/custom_components/airnut/__init__.py", line 111, in func_weather
    weathestate = wet_dataA[jsonData['weather']]
KeyError: '阴'

**Comment by gitgayhub** [comment]
我这没问题，你试试https://api.help.bj.cn/apis/weather/?id=城市代码 看看返回的json正常不

**Comment by houoop** [comment]
已解决

**Comment by houoop** [comment]
我看你代码里面加入了保持亮屏的代码, 我更新了怎么没效果

**Comment by gitgayhub** [comment]
> 我看了一下,找到原因了,是因为wet_dataA的字典中,没有"阴"这个键

请问阴对应的代码是几？

**Comment by houoop** [comment]
> > 我看了一下,找到原因了,是因为wet_dataA的字典中,没有"阴"这个键
> 
> 请问阴对应的代码是几？

我提交了一个pull request ,和多云同一个图标
