### ISSUE TITLE
怎么关闭自动亮屏？

### ISSUE THREAD

**Issue by myseil** [zllikey/AirnutFun#3]
这个怎么设置不自动亮屏？放电脑旁边太烦了，一会亮一会熄的！
还有升级最新版本后，天气预报不准了！

**Comment by zllikey** [comment]
def deal_write_sockets(self, write_sockets):
        #发送数据
        #持续检测，持续亮屏，风扇问题晚上很吵 ，调整 SCAN_INTERVAL = datetime.timedelta(seconds=60)  里面的数字
        global socket_ip_dict
        global weathestate
        check_msg = {"common": {"device": "Fun_pm25", "protocol": "detect"}, "param": {"fromport": 8023, "airid": 1010695, "fromhost": "192.168.1.32"}}
        for sock in write_sockets:
            if sock == self._socketServer:
                continue
            try:
                sock.send(self.object_to_json_data(check_msg))
            except:
                del socket_ip_dict[sock]
这里 代码,删掉  下面几行

            try:
                sock.send(self.object_to_json_data(check_msg))
            except:
                del socket_ip_dict[sock]


即可
或者
SCAN_INTERVAL = datetime.timedelta(seconds=120)
改大一点
，1小时一次 3600 秒
