### ISSUE TITLE
你能指导我如何设置更新世界上每个城市的天气吗？

### ISSUE THREAD

**Issue by kaiba4786** [zllikey/AirnutFun#4]
你的工作是值得尊敬的。
你能指导我如何设置更新世界上每个城市的天气吗？

**Comment by zllikey** [comment]
天气代码表格里有全球城市天气代码

**Comment by kaiba4786** [comment]
> 天气代码表格里有全球城市天气代码

谢谢，我已经改用https://openweathermap.org/的API了
