### ISSUE TITLE
home_assistant重启后，airnut没有自动连接home_assistant

### ISSUE THREAD

**Issue by kaiba4786** [zllikey/AirnutFun#5]
home_assistant重启后，airnut没有自动连接home_assistant, 我必须重新启动airnut (按住背面的按钮 5 秒钟).

您能指导我如何在 home_assistant 重新启动后让 airnut 自行连接到 home_assistant 吗？

**Comment by zllikey** [comment]
自动的，启动ha后，ha运行了代理服务器后，会经过配置文件的ip信息，立即对空气果fun发送一次对时任务，然后就会上传数据

**Comment by kaiba4786** [comment]
我检查了
该问题仅在执行 rebo​​ot system 时出现
restart home assistant, 一切正常

**Comment by kaiba4786** [comment]
我的问题解决了：在路由器设置中我阻止了 airnut 连接到互联网
