### ISSUE TITLE
当与 hass 的连接丢失时，时钟显示错误的时间

### ISSUE THREAD

**Issue by kaiba4786** [zllikey/AirnutFun#6]
又是我

hass重启时间长了，时钟会和hass失去联系。
手表背光不亮，表盘显示时间自动变为中国时间（我住在越南，代码中选择越南时区）.
我觉得：时钟和越南时间的时差是时钟无法重连hass的原因（如果hass的启动时间过长）.
即使与 nas 的连接丢失，是否有任何解决方案可以在表盘上保持时间（在越南继续显示时间）？

谢谢

**Comment by zllikey** [comment]
ha重启时间长不长 应该不会丢失时间，ha重启后会对配置文件中的空气果IP进行一次发送对时设置，所以无论你怎么重启ha，只要ha正常启动一次，就会对空气果进行一次对时

**Comment by kaiba4786** [comment]
> ha重启时间长不长 应该不会丢失时间，ha重启后会对配置文件中的空气果IP进行一次发送对时设置，所以无论你怎么重启ha，只要ha正常启动一次，就会对空气果进行一次对时

感谢你的回复
对不起我的中文不好
我认为：只有在中国，你的答案才是正确的：当arinut和Hass失去联系时，hass和arinut的时间仍然相同（GMT+8），所以arinut可以处理来自hass的同步命令。

但我的情况是，arinut 上的时间比 hass 快 1 小时（60 分钟），所以 arinut 没有处理 hass 发送的同步命令。 我已经将时间设置为 GMT +7，但每次我关闭 hass，arinut 都会自动将时间增加 1 小时（60 分钟）

你能通过将时区更改为 7 来重现我的问题吗:
 return int((datetime.datetime.now() + datetime.timedelta(hours=7)).timestamp())

我想：当hass关闭时，arinut连接到中国时间服务器以同步arinut上的时间，你能告诉我中国时间服务器的域名吗？我将阻止时间服务器域，这将解决我的问题

**Comment by kaiba4786** [comment]
我的问题解决了：在路由器设置中我阻止了 airnut 连接到互联网
